services:
  web:
    image: ruby:3.4
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash -c "bundle update --bundler && bundle exec jekyll serve --watch --config _config.yml -H 0.0.0.0 -P 8010"
    ports:
      - "8010:8010"
    stdin_open: true
    tty: true